# Generated by Django 6.0.1 on 2026-01-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebankaccount',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employeebankaccount',
            name='employee',
        ),
        migrations.DeleteModel(
            name='BankChangeRequest',
        ),
        migrations.DeleteModel(
            name='EmployeeBankAccount',
        ),
    ]
