# Generated by Django 6.0.1 on 2026-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_and_more'),
        ('employees', '0002_alter_employee_unique_together_employee_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_emp_code_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_bank_account',
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'emp_code')},
        ),
        migrations.RemoveField(
            model_name='employeedraft',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='employeedraft',
            name='bank_ifsc',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
