# Generated by Django 6.0.1 on 2026-01-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0003_auditlog_employeedraft_employee_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['emp_code']},
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_company_e6f766_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_uan_num_a18f1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_esic_nu_e88e58_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeedraft',
            name='employees_e_company_b7fb8e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='employeedraft',
            unique_together={('company', 'emp_code')},
        ),
        migrations.AddField(
            model_name='employee',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedraft',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employeedraft',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='employeedraft',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='employeedraft',
            name='reviewed_by',
        ),
    ]
