# Generated by Django 6.0.1 on 2026-01-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeechangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeechangerequest',
            old_name='applied_at',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='employeechangerequest',
            name='applied_by',
        ),
        migrations.AddField(
            model_name='employeechangerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeechangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeechangerequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeechangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
