# Generated by Django 6.0.1 on 2026-02-13 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
        ('employees', '0003_remove_employee_unique_emp_code_per_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankchangerequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='bankchangerequest',
            name='effective_from_month',
        ),
        migrations.AddField(
            model_name='bankchangerequest',
            name='effective_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankchangerequest',
            name='effective_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankchangerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_change_requests', to='employees.employee'),
        ),
    ]
