# Generated by Django 6.0.1 on 2026-02-20 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_bankchangerequest_options_and_more'),
        ('employees', '0003_remove_employee_unique_emp_code_per_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebankaccount',
            options={'ordering': ['-effective_from_month']},
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='ifsc',
            field=models.CharField(max_length=11),
        ),
        migrations.AddIndex(
            model_name='employeebankaccount',
            index=models.Index(fields=['employee', 'is_active'], name='banking_emp_employe_d697df_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee',), name='unique_active_bank_account_per_employee'),
        ),
    ]
