# Generated by Django 6.0.1 on 2026-02-23 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_employeebankaccount_options_and_more'),
        ('employees', '0003_remove_employee_unique_emp_code_per_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeebankaccount',
            name='unique_active_bank_account_per_employee',
        ),
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'account_number'), name='unique_active_bank_account_per_employee'),
        ),
    ]
