# Generated by Django 6.0.1 on 2026-02-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_companies_c_organis_c941ed_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['site_code']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='serial_no',
            new_name='site_code',
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('organisation', 'site_code')},
        ),
    ]
