# Generated by Django 6.0.3 on 2026-03-08 00:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationuser',
            name='notify_approval_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='notify_payroll_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='notify_salary_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='notify_salary_hold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='companies.organisation')),
            ],
            options={
                'unique_together': {('organisation', 'email')},
            },
        ),
    ]
