# Generated by Django 6.0.1 on 2026-01-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salarytransaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='bank_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
