# Generated by Django 6.0.1 on 2026-02-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Export'), ('EXPORTED', 'Exported to Bank'), ('COMPLETED', 'Completed'), ('REVERSED', 'Reversed'), ('PENDING', 'Pending'), ('HOLD', 'Hold'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
