# Generated by Django 6.0.1 on 2026-01-19 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeebankaccount_approved_by_and_more'),
        ('payroll', '0002_alter_salarytransaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='ifsc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['employee'], name='payroll_sal_employe_419d15_idx'),
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['batch'], name='payroll_sal_batch_i_991e72_idx'),
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['status'], name='payroll_sal_status_bb8f81_idx'),
        ),
    ]
