# Generated by Django 6.0.1 on 2026-01-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeebankaccount_approved_by_and_more'),
        ('payroll', '0003_salarytransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarybatch',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterModelOptions(
            name='salarytransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='salarybatch',
            name='reversal_reason',
            field=models.TextField(blank=True, help_text='Reason for reversing this batch (admin only)', null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salarybatch',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salarybatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('EXPORTED', 'Exported to Bank'), ('COMPLETED', 'Completed'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarybatch',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payroll.salarybatch'),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_transactions', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='salarytransaction',
            unique_together={('batch', 'employee')},
        ),
    ]
